language: ruby
rvm:
  - 2.1.1
  - ruby
script:
  - RAILS_ENV=test bundle exec rake test
before_script:
  - RAILS_ENV=test bundle exec rake db:create db:migrate
before_install:
  - rvm install ruby-2.1.1
